name: Post Build Action

run-name: 'Post Build Action -- ${{github.event.workflow_run.head_branch}}'

on:
   workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed

        
        
jobs:
  post-build:
    name: Post Build Actions
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.event.workflow_run.head_repository.full_name}}
          ref: ${{github.event.workflow_run.head_branch}}

      - name: Build Protoc Docker container
        uses: docker/build-push-action@v6
        with:
            push: false
            context: .
            file: protoc.dockerfile
            tags: tinkar-schema-protoc:latest
    
      - name: Generate Java Code
        run: |
              docker run -v ./src/main/java-generated:/home/proto-builder/src/main/java-generated --rm tinkar-schema-protoc:latest
          
      - name: list java code
        run: |
              ls src/main/java-generated
      
      - name: IKMDEV Post Build Action
        id: ikmdev_post_build
        uses: ikmdev/maven-post-build-action@v3.1.0
        with:
            nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
            branch_name: ${{github.event.workflow_run.head_branch}}
            github_token: ${{secrets.GITHUB_TOKEN}}
            maven_central_username: ${{secrets.MC_SECRET_USERNAME}}
            maven_central_password: ${{secrets.MC_SECRET_PASSWORD}}
            gpg_key: ${{secrets.GPG_KEY}}
            gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
            sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
            sonarcloud_sources: 'src/main/java-generated'
            sonarcloud_tests: ${{ '' }}